version: 2
registries:
  ft-inntektsmelding-frontend:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/ft-inntektsmelding-frontend
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: "/app"
    registries:
      - ft-inntektsmelding-frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    groups:
      app-prod-minor-deps:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      app-prod-major-deps:
        dependency-type: "production"
        update-types:
          - "major"
      app-dev-deps:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      app-dev-major-deps:
        dependency-type: "development"
        update-types:
          - "major"
  - package-ecosystem: npm
    directory: "/server"
    registries:
      - ft-inntektsmelding-frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    groups:
      server-prod-minor-deps:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      server-prod-major-deps:
        dependency-type: "production"
        update-types:
          - "major"
      server-dev-deps:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      server-dev-major-deps:
        dependency-type: "development"
        update-types:
          - "major"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
