/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NyIdImport } from './routes/ny.$id'
import { Route as KvitteringIdImport } from './routes/kvittering.$id'
import { Route as EndreIdImport } from './routes/endre.$id'

// Create/Update Routes

const NyIdRoute = NyIdImport.update({
  path: '/ny/$id',
  getParentRoute: () => rootRoute,
} as any)

const KvitteringIdRoute = KvitteringIdImport.update({
  path: '/kvittering/$id',
  getParentRoute: () => rootRoute,
} as any)

const EndreIdRoute = EndreIdImport.update({
  path: '/endre/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/endre/$id': {
      preLoaderRoute: typeof EndreIdImport
      parentRoute: typeof rootRoute
    }
    '/kvittering/$id': {
      preLoaderRoute: typeof KvitteringIdImport
      parentRoute: typeof rootRoute
    }
    '/ny/$id': {
      preLoaderRoute: typeof NyIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  EndreIdRoute,
  KvitteringIdRoute,
  NyIdRoute,
])

/* prettier-ignore-end */
