/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpprettRouteImport } from './routes/opprett'
import { Route as IdRouteImport } from './routes/$id'
import { Route as OpprettIndexRouteImport } from './routes/opprett.index'
import { Route as IdIndexRouteImport } from './routes/$id.index'
import { Route as RefusjonOmsorgspengerOrganisasjonsnummerRouteImport } from './routes/refusjon-omsorgspenger.$organisasjonsnummer'
import { Route as IdVisRouteImport } from './routes/$id.vis'
import { Route as IdRefusjonRouteImport } from './routes/$id.refusjon'
import { Route as IdOppsummeringAgiRouteImport } from './routes/$id.oppsummering-agi'
import { Route as IdOppsummeringRouteImport } from './routes/$id.oppsummering'
import { Route as IdKvitteringRouteImport } from './routes/$id.kvittering'
import { Route as IdInntektOgRefusjonRouteImport } from './routes/$id.inntekt-og-refusjon'
import { Route as IdDineOpplysningerRouteImport } from './routes/$id.dine-opplysninger'
import { Route as RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRouteImport } from './routes/refusjon-omsorgspenger.$organisasjonsnummer.6-kvittering'
import { Route as RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRouteImport } from './routes/refusjon-omsorgspenger.$organisasjonsnummer.5-oppsummering'
import { Route as RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRouteImport } from './routes/refusjon-omsorgspenger.$organisasjonsnummer.4-refusjon'
import { Route as RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRouteImport } from './routes/refusjon-omsorgspenger.$organisasjonsnummer.3-omsorgsdager'
import { Route as RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRouteImport } from './routes/refusjon-omsorgspenger.$organisasjonsnummer.2-ansatt-og-arbeidsgiver'
import { Route as RefusjonOmsorgspengerOrganisasjonsnummer1IntroRouteImport } from './routes/refusjon-omsorgspenger.$organisasjonsnummer.1-intro'
import { Route as RefusjonOmsorgspengerOrganisasjonsnummerIdRouteImport } from './routes/refusjon-omsorgspenger.$organisasjonsnummer.$id'

const OpprettRoute = OpprettRouteImport.update({
  id: '/opprett',
  path: '/opprett',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpprettIndexRoute = OpprettIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpprettRoute,
} as any)
const IdIndexRoute = IdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdRoute,
} as any)
const RefusjonOmsorgspengerOrganisasjonsnummerRoute =
  RefusjonOmsorgspengerOrganisasjonsnummerRouteImport.update({
    id: '/refusjon-omsorgspenger/$organisasjonsnummer',
    path: '/refusjon-omsorgspenger/$organisasjonsnummer',
    getParentRoute: () => rootRouteImport,
  } as any)
const IdVisRoute = IdVisRouteImport.update({
  id: '/vis',
  path: '/vis',
  getParentRoute: () => IdRoute,
} as any)
const IdRefusjonRoute = IdRefusjonRouteImport.update({
  id: '/refusjon',
  path: '/refusjon',
  getParentRoute: () => IdRoute,
} as any)
const IdOppsummeringAgiRoute = IdOppsummeringAgiRouteImport.update({
  id: '/oppsummering-agi',
  path: '/oppsummering-agi',
  getParentRoute: () => IdRoute,
} as any)
const IdOppsummeringRoute = IdOppsummeringRouteImport.update({
  id: '/oppsummering',
  path: '/oppsummering',
  getParentRoute: () => IdRoute,
} as any)
const IdKvitteringRoute = IdKvitteringRouteImport.update({
  id: '/kvittering',
  path: '/kvittering',
  getParentRoute: () => IdRoute,
} as any)
const IdInntektOgRefusjonRoute = IdInntektOgRefusjonRouteImport.update({
  id: '/inntekt-og-refusjon',
  path: '/inntekt-og-refusjon',
  getParentRoute: () => IdRoute,
} as any)
const IdDineOpplysningerRoute = IdDineOpplysningerRouteImport.update({
  id: '/dine-opplysninger',
  path: '/dine-opplysninger',
  getParentRoute: () => IdRoute,
} as any)
const RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRoute =
  RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRouteImport.update({
    id: '/6-kvittering',
    path: '/6-kvittering',
    getParentRoute: () => RefusjonOmsorgspengerOrganisasjonsnummerRoute,
  } as any)
const RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRoute =
  RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRouteImport.update({
    id: '/5-oppsummering',
    path: '/5-oppsummering',
    getParentRoute: () => RefusjonOmsorgspengerOrganisasjonsnummerRoute,
  } as any)
const RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRoute =
  RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRouteImport.update({
    id: '/4-refusjon',
    path: '/4-refusjon',
    getParentRoute: () => RefusjonOmsorgspengerOrganisasjonsnummerRoute,
  } as any)
const RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRoute =
  RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRouteImport.update({
    id: '/3-omsorgsdager',
    path: '/3-omsorgsdager',
    getParentRoute: () => RefusjonOmsorgspengerOrganisasjonsnummerRoute,
  } as any)
const RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRoute =
  RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRouteImport.update(
    {
      id: '/2-ansatt-og-arbeidsgiver',
      path: '/2-ansatt-og-arbeidsgiver',
      getParentRoute: () => RefusjonOmsorgspengerOrganisasjonsnummerRoute,
    } as any,
  )
const RefusjonOmsorgspengerOrganisasjonsnummer1IntroRoute =
  RefusjonOmsorgspengerOrganisasjonsnummer1IntroRouteImport.update({
    id: '/1-intro',
    path: '/1-intro',
    getParentRoute: () => RefusjonOmsorgspengerOrganisasjonsnummerRoute,
  } as any)
const RefusjonOmsorgspengerOrganisasjonsnummerIdRoute =
  RefusjonOmsorgspengerOrganisasjonsnummerIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => RefusjonOmsorgspengerOrganisasjonsnummerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$id': typeof IdRouteWithChildren
  '/opprett': typeof OpprettRouteWithChildren
  '/$id/dine-opplysninger': typeof IdDineOpplysningerRoute
  '/$id/inntekt-og-refusjon': typeof IdInntektOgRefusjonRoute
  '/$id/kvittering': typeof IdKvitteringRoute
  '/$id/oppsummering': typeof IdOppsummeringRoute
  '/$id/oppsummering-agi': typeof IdOppsummeringAgiRoute
  '/$id/refusjon': typeof IdRefusjonRoute
  '/$id/vis': typeof IdVisRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer': typeof RefusjonOmsorgspengerOrganisasjonsnummerRouteWithChildren
  '/$id/': typeof IdIndexRoute
  '/opprett/': typeof OpprettIndexRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/$id': typeof RefusjonOmsorgspengerOrganisasjonsnummerIdRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/1-intro': typeof RefusjonOmsorgspengerOrganisasjonsnummer1IntroRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/2-ansatt-og-arbeidsgiver': typeof RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/3-omsorgsdager': typeof RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/4-refusjon': typeof RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/5-oppsummering': typeof RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/6-kvittering': typeof RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRoute
}
export interface FileRoutesByTo {
  '/$id/dine-opplysninger': typeof IdDineOpplysningerRoute
  '/$id/inntekt-og-refusjon': typeof IdInntektOgRefusjonRoute
  '/$id/kvittering': typeof IdKvitteringRoute
  '/$id/oppsummering': typeof IdOppsummeringRoute
  '/$id/oppsummering-agi': typeof IdOppsummeringAgiRoute
  '/$id/refusjon': typeof IdRefusjonRoute
  '/$id/vis': typeof IdVisRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer': typeof RefusjonOmsorgspengerOrganisasjonsnummerRouteWithChildren
  '/$id': typeof IdIndexRoute
  '/opprett': typeof OpprettIndexRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/$id': typeof RefusjonOmsorgspengerOrganisasjonsnummerIdRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/1-intro': typeof RefusjonOmsorgspengerOrganisasjonsnummer1IntroRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/2-ansatt-og-arbeidsgiver': typeof RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/3-omsorgsdager': typeof RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/4-refusjon': typeof RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/5-oppsummering': typeof RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/6-kvittering': typeof RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$id': typeof IdRouteWithChildren
  '/opprett': typeof OpprettRouteWithChildren
  '/$id/dine-opplysninger': typeof IdDineOpplysningerRoute
  '/$id/inntekt-og-refusjon': typeof IdInntektOgRefusjonRoute
  '/$id/kvittering': typeof IdKvitteringRoute
  '/$id/oppsummering': typeof IdOppsummeringRoute
  '/$id/oppsummering-agi': typeof IdOppsummeringAgiRoute
  '/$id/refusjon': typeof IdRefusjonRoute
  '/$id/vis': typeof IdVisRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer': typeof RefusjonOmsorgspengerOrganisasjonsnummerRouteWithChildren
  '/$id/': typeof IdIndexRoute
  '/opprett/': typeof OpprettIndexRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/$id': typeof RefusjonOmsorgspengerOrganisasjonsnummerIdRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/1-intro': typeof RefusjonOmsorgspengerOrganisasjonsnummer1IntroRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/2-ansatt-og-arbeidsgiver': typeof RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/3-omsorgsdager': typeof RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/4-refusjon': typeof RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/5-oppsummering': typeof RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRoute
  '/refusjon-omsorgspenger/$organisasjonsnummer/6-kvittering': typeof RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$id'
    | '/opprett'
    | '/$id/dine-opplysninger'
    | '/$id/inntekt-og-refusjon'
    | '/$id/kvittering'
    | '/$id/oppsummering'
    | '/$id/oppsummering-agi'
    | '/$id/refusjon'
    | '/$id/vis'
    | '/refusjon-omsorgspenger/$organisasjonsnummer'
    | '/$id/'
    | '/opprett/'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/$id'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/1-intro'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/2-ansatt-og-arbeidsgiver'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/3-omsorgsdager'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/4-refusjon'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/5-oppsummering'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/6-kvittering'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$id/dine-opplysninger'
    | '/$id/inntekt-og-refusjon'
    | '/$id/kvittering'
    | '/$id/oppsummering'
    | '/$id/oppsummering-agi'
    | '/$id/refusjon'
    | '/$id/vis'
    | '/refusjon-omsorgspenger/$organisasjonsnummer'
    | '/$id'
    | '/opprett'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/$id'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/1-intro'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/2-ansatt-og-arbeidsgiver'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/3-omsorgsdager'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/4-refusjon'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/5-oppsummering'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/6-kvittering'
  id:
    | '__root__'
    | '/$id'
    | '/opprett'
    | '/$id/dine-opplysninger'
    | '/$id/inntekt-og-refusjon'
    | '/$id/kvittering'
    | '/$id/oppsummering'
    | '/$id/oppsummering-agi'
    | '/$id/refusjon'
    | '/$id/vis'
    | '/refusjon-omsorgspenger/$organisasjonsnummer'
    | '/$id/'
    | '/opprett/'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/$id'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/1-intro'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/2-ansatt-og-arbeidsgiver'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/3-omsorgsdager'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/4-refusjon'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/5-oppsummering'
    | '/refusjon-omsorgspenger/$organisasjonsnummer/6-kvittering'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IdRoute: typeof IdRouteWithChildren
  OpprettRoute: typeof OpprettRouteWithChildren
  RefusjonOmsorgspengerOrganisasjonsnummerRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/opprett': {
      id: '/opprett'
      path: '/opprett'
      fullPath: '/opprett'
      preLoaderRoute: typeof OpprettRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opprett/': {
      id: '/opprett/'
      path: '/'
      fullPath: '/opprett/'
      preLoaderRoute: typeof OpprettIndexRouteImport
      parentRoute: typeof OpprettRoute
    }
    '/$id/': {
      id: '/$id/'
      path: '/'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdIndexRouteImport
      parentRoute: typeof IdRoute
    }
    '/refusjon-omsorgspenger/$organisasjonsnummer': {
      id: '/refusjon-omsorgspenger/$organisasjonsnummer'
      path: '/refusjon-omsorgspenger/$organisasjonsnummer'
      fullPath: '/refusjon-omsorgspenger/$organisasjonsnummer'
      preLoaderRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/vis': {
      id: '/$id/vis'
      path: '/vis'
      fullPath: '/$id/vis'
      preLoaderRoute: typeof IdVisRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/refusjon': {
      id: '/$id/refusjon'
      path: '/refusjon'
      fullPath: '/$id/refusjon'
      preLoaderRoute: typeof IdRefusjonRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/oppsummering-agi': {
      id: '/$id/oppsummering-agi'
      path: '/oppsummering-agi'
      fullPath: '/$id/oppsummering-agi'
      preLoaderRoute: typeof IdOppsummeringAgiRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/oppsummering': {
      id: '/$id/oppsummering'
      path: '/oppsummering'
      fullPath: '/$id/oppsummering'
      preLoaderRoute: typeof IdOppsummeringRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/kvittering': {
      id: '/$id/kvittering'
      path: '/kvittering'
      fullPath: '/$id/kvittering'
      preLoaderRoute: typeof IdKvitteringRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/inntekt-og-refusjon': {
      id: '/$id/inntekt-og-refusjon'
      path: '/inntekt-og-refusjon'
      fullPath: '/$id/inntekt-og-refusjon'
      preLoaderRoute: typeof IdInntektOgRefusjonRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/dine-opplysninger': {
      id: '/$id/dine-opplysninger'
      path: '/dine-opplysninger'
      fullPath: '/$id/dine-opplysninger'
      preLoaderRoute: typeof IdDineOpplysningerRouteImport
      parentRoute: typeof IdRoute
    }
    '/refusjon-omsorgspenger/$organisasjonsnummer/6-kvittering': {
      id: '/refusjon-omsorgspenger/$organisasjonsnummer/6-kvittering'
      path: '/6-kvittering'
      fullPath: '/refusjon-omsorgspenger/$organisasjonsnummer/6-kvittering'
      preLoaderRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRouteImport
      parentRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerRoute
    }
    '/refusjon-omsorgspenger/$organisasjonsnummer/5-oppsummering': {
      id: '/refusjon-omsorgspenger/$organisasjonsnummer/5-oppsummering'
      path: '/5-oppsummering'
      fullPath: '/refusjon-omsorgspenger/$organisasjonsnummer/5-oppsummering'
      preLoaderRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRouteImport
      parentRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerRoute
    }
    '/refusjon-omsorgspenger/$organisasjonsnummer/4-refusjon': {
      id: '/refusjon-omsorgspenger/$organisasjonsnummer/4-refusjon'
      path: '/4-refusjon'
      fullPath: '/refusjon-omsorgspenger/$organisasjonsnummer/4-refusjon'
      preLoaderRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRouteImport
      parentRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerRoute
    }
    '/refusjon-omsorgspenger/$organisasjonsnummer/3-omsorgsdager': {
      id: '/refusjon-omsorgspenger/$organisasjonsnummer/3-omsorgsdager'
      path: '/3-omsorgsdager'
      fullPath: '/refusjon-omsorgspenger/$organisasjonsnummer/3-omsorgsdager'
      preLoaderRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRouteImport
      parentRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerRoute
    }
    '/refusjon-omsorgspenger/$organisasjonsnummer/2-ansatt-og-arbeidsgiver': {
      id: '/refusjon-omsorgspenger/$organisasjonsnummer/2-ansatt-og-arbeidsgiver'
      path: '/2-ansatt-og-arbeidsgiver'
      fullPath: '/refusjon-omsorgspenger/$organisasjonsnummer/2-ansatt-og-arbeidsgiver'
      preLoaderRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRouteImport
      parentRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerRoute
    }
    '/refusjon-omsorgspenger/$organisasjonsnummer/1-intro': {
      id: '/refusjon-omsorgspenger/$organisasjonsnummer/1-intro'
      path: '/1-intro'
      fullPath: '/refusjon-omsorgspenger/$organisasjonsnummer/1-intro'
      preLoaderRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer1IntroRouteImport
      parentRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerRoute
    }
    '/refusjon-omsorgspenger/$organisasjonsnummer/$id': {
      id: '/refusjon-omsorgspenger/$organisasjonsnummer/$id'
      path: '/$id'
      fullPath: '/refusjon-omsorgspenger/$organisasjonsnummer/$id'
      preLoaderRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerIdRouteImport
      parentRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerRoute
    }
  }
}

interface IdRouteChildren {
  IdDineOpplysningerRoute: typeof IdDineOpplysningerRoute
  IdInntektOgRefusjonRoute: typeof IdInntektOgRefusjonRoute
  IdKvitteringRoute: typeof IdKvitteringRoute
  IdOppsummeringRoute: typeof IdOppsummeringRoute
  IdOppsummeringAgiRoute: typeof IdOppsummeringAgiRoute
  IdRefusjonRoute: typeof IdRefusjonRoute
  IdVisRoute: typeof IdVisRoute
  IdIndexRoute: typeof IdIndexRoute
}

const IdRouteChildren: IdRouteChildren = {
  IdDineOpplysningerRoute: IdDineOpplysningerRoute,
  IdInntektOgRefusjonRoute: IdInntektOgRefusjonRoute,
  IdKvitteringRoute: IdKvitteringRoute,
  IdOppsummeringRoute: IdOppsummeringRoute,
  IdOppsummeringAgiRoute: IdOppsummeringAgiRoute,
  IdRefusjonRoute: IdRefusjonRoute,
  IdVisRoute: IdVisRoute,
  IdIndexRoute: IdIndexRoute,
}

const IdRouteWithChildren = IdRoute._addFileChildren(IdRouteChildren)

interface OpprettRouteChildren {
  OpprettIndexRoute: typeof OpprettIndexRoute
}

const OpprettRouteChildren: OpprettRouteChildren = {
  OpprettIndexRoute: OpprettIndexRoute,
}

const OpprettRouteWithChildren =
  OpprettRoute._addFileChildren(OpprettRouteChildren)

interface RefusjonOmsorgspengerOrganisasjonsnummerRouteChildren {
  RefusjonOmsorgspengerOrganisasjonsnummerIdRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummerIdRoute
  RefusjonOmsorgspengerOrganisasjonsnummer1IntroRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer1IntroRoute
  RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRoute
  RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRoute
  RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRoute
  RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRoute
  RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRoute: typeof RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRoute
}

const RefusjonOmsorgspengerOrganisasjonsnummerRouteChildren: RefusjonOmsorgspengerOrganisasjonsnummerRouteChildren =
  {
    RefusjonOmsorgspengerOrganisasjonsnummerIdRoute:
      RefusjonOmsorgspengerOrganisasjonsnummerIdRoute,
    RefusjonOmsorgspengerOrganisasjonsnummer1IntroRoute:
      RefusjonOmsorgspengerOrganisasjonsnummer1IntroRoute,
    RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRoute:
      RefusjonOmsorgspengerOrganisasjonsnummer2AnsattOgArbeidsgiverRoute,
    RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRoute:
      RefusjonOmsorgspengerOrganisasjonsnummer3OmsorgsdagerRoute,
    RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRoute:
      RefusjonOmsorgspengerOrganisasjonsnummer4RefusjonRoute,
    RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRoute:
      RefusjonOmsorgspengerOrganisasjonsnummer5OppsummeringRoute,
    RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRoute:
      RefusjonOmsorgspengerOrganisasjonsnummer6KvitteringRoute,
  }

const RefusjonOmsorgspengerOrganisasjonsnummerRouteWithChildren =
  RefusjonOmsorgspengerOrganisasjonsnummerRoute._addFileChildren(
    RefusjonOmsorgspengerOrganisasjonsnummerRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IdRoute: IdRouteWithChildren,
  OpprettRoute: OpprettRouteWithChildren,
  RefusjonOmsorgspengerOrganisasjonsnummerRoute:
    RefusjonOmsorgspengerOrganisasjonsnummerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
