name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Yarn for GitHub Packages
        run: |
          yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.navikt.npmAlwaysAuth true
          yarn config set npmScopes.navikt.npmAuthToken ${{ secrets.READER_TOKEN }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: ls
        run: ls -la
